export { default as DashboardPage } from './DashboardPage';
export { default as CreateContractPage } from './CreateContractPage';
export { default as ContractsPage } from './ContractsPage';
export { default as ApprovalsPage } from './ApprovalsPage';
export { default as SettingsPage } from './SettingsPage';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as ContractDetailPage } from './ContractDetailPage';
export { default as VerificationPage } from './VerificationPage';
